---
title: "Lead Poisoning and Crime Rates"
author: "Rahul Agasthya, Manasdeep Deb, Ajay Roopesh Mohan, Jay Rodge, Nicholas Tating"
date: "10/17/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../images")
library(GGally)
library(corrplot)
library(RColorBrewer)
```

```{r importing the data}
crimeFile <- "../data/Index_Crimes_by_County_and_Agency__Beginning_1990.csv"
leadFile <- "../data/Childhood_Blood_Lead_Testing_and_Elevated_Incidence_by_Zip_Code__Beginning_2000.csv"
populationFile <- "../data/Annual_Population_Estimates_for_New_York_State_and_Counties__Beginning_1970.csv"

crimes <- read.csv(file = crimeFile, stringsAsFactors = FALSE)
lead <- read.csv(file = leadFile, stringsAsFactors = FALSE)
population <- read.csv(file = populationFile, stringsAsFactors = FALSE)
```

```{r crime_head}
head(crimes)
```

```{r lead_head}
#head(lead)
ncol(lead)
```

```{r pop_head}
head(population)
```

```{r removing_columns}
toDropLead <- c("Zip.Code.Location", "County.Location")
lead <-lead[, !(names(lead) %in% toDropLead)]

toDropCrimes <- c("Agency", "Region")
crimes <- crimes[, !(names(crimes) %in% toDropCrimes)]

# thought about removing Program.Type from the population table, though the numbers could affect our analysis https://en.wikipedia.org/wiki/Intercensal_estimate
```

```{r set_data_types}
lead$County.Code <- as.character(lead$County.Code)
lead$Zip <- as.character(lead$Zip)

population$FIPS.Code <- as.character(population$FIPS.Code)
```

```{r crimes_summary}
summary(crimes)
```

```{r lead_summary}

```

```{r population_summary}
summary(population)
```

```{r lead_na_omit}
lead_clean <- na.omit(lead)
summary(lead_clean)
# note that removing rows with NA brings us from 29807 observations to 227...
```

```{r}
drops <- c("Agency","Index Total")
crimes <-crimes[ , !(names(crimes) %in% drops)]
```

```{r}
#list of common counties in Lead and Crime dataset
 c(intersect(lead_clean$County, crimes$County))
```

```{r}
commonCounties <- c("Niagara", "Onondaga", "Erie", "Orange","Oneida","Westchester", "Montgomery","Monroe","Albany",      "Fulton","Broome", "Ulster","Dutchess", "Chautauqua", "Rockland")
```

```{r}
lead_processed = subset(lead_clean, commonCounties %in% lead_clean$County)
rownames(lead_processed) <- 1:nrow(lead_processed)
lead_processed
```

```{r}
Crime_processed = subset(crimes, commonCounties %in% crimes$County)
rownames(Crime_processed) <- 1:nrow(Crime_processed)
Crime_processed
```

```{r}
Merge_dataframe <- merge(lead_processed,Crime_processed,by=c("County"))
Merge_dataframe
```

```{r}
ggcorr(Merge_dataframe$)
```

```{r}

```

```{r}

```